### ISSUE TITLE
Top 5 pods visualization not displaying correctly Falco 

### ISSUE THREAD

**Issue by Fiskeboat** [onzack/grafana-dashboards#8]
Hello!
I love the Falco dashboard, however I am having some difficulties with it.
Expected view: 
![pikk](https://github.com/user-attachments/assets/201733fd-f10b-42dc-a1e3-d5e251b3193b)

Actual View:
![pikk2](https://github.com/user-attachments/assets/ec22a5a6-b4b7-4256-b586-673a84506c4e)

Any help would be appreciated. Using Grafana V.11, Loki 2.9.6 and Falco 0.370

**Comment by R-Studio** [comment]
@Fiskeboat Hello, thank you for your interest and sorry for the late reply👋
I understand you were having issues with the Falco dashboard, and I'm happy to tell you that I've identified the root cause and fixed it.  
_The problem was related to a recent change in Grafana v11 where [instant queries for Loki logs were removed](https://github.com/grafana/grafana/pull/90137)._   

Let me know if you need any further assistance! 😊
